### ISSUE TITLE
Set github template

### ISSUE THREAD

**Issue by seo2im** [ReactPiscine/ReactPscine#1]
## Description
Set template of github basics

## TODO
- [ ] set issue temp;ate
- [ ] set pr template
- [ ] add commit template file
