### ISSUE TITLE
Set piscine structure

### ISSUE THREAD

**Issue by seo2im** [ReactPiscine/ReactPscine#3]
## Description
Set piscine structure & plan

## Todo
- [ ] Set each piscine management
- [ ] Check what need
- [ ] Set curriculum of each piscine

**Comment by seo2im** [comment]
**Subject:** https://www.notion.so/React-Pscine-36b8a8427c44402fbfee266172eedbf0
