### ISSUE TITLE
Set page planning

### ISSUE THREAD

**Issue by seo2im** [ReactPiscine/ReactPscine#4]
## Description
Write page plan subjects.

## Todo
- [x] Write page flow
- [x] Write page functions documentation
- [x] Write wire frame
- [ ] page design

**Comment by seo2im** [comment]
page flow link: https://www.notion.so/React-Pscine-09efb868affa4a82829981266c1ee158

**Comment by seo2im** [comment]
page function documentation link: https://www.notion.so/Piscine-f453e080c72f4b98a5601771c0337f2d

**Comment by seo2im** [comment]
wire frame link: https://www.figma.com/file/skUUqP3C4jxymy45FV7oTG/React-Piscine?node-id=0%3A1

**Comment by seo2im** [comment]
Design is later when after end of environment & testing
