### ISSUE TITLE
Set DB & API planning

### ISSUE THREAD

**Issue by seo2im** [ReactPiscine/ReactPscine#5]
## Description
Write DB & API planning subjects
- After page functions documentation in #4 

## Todo
- [x] Write usecase
- [x] Write DB model
- [x] Write API Spec
- [x] Write Sequence diagram
- [ ] api documentation write

**Comment by seo2im** [comment]
usecae link: https://www.notion.so/Usecase-149505c9fc254ae8ba5da50055133708

**Comment by seo2im** [comment]
DB model link: https://www.notion.so/DB-Model-9c423bd0c9964ffebf2d5f3e553b309d

**Comment by seo2im** [comment]
API spec link: https://www.notion.so/API-Spec-63e7dbd0303b4fa7a8705e77c6d01292

**Comment by seo2im** [comment]
sequence diagram: https://www.figma.com/file/skUUqP3C4jxymy45FV7oTG/React-Piscine?node-id=0%3A1

**Comment by seo2im** [comment]
api documentation is set after envieonment setting later
