### ISSUE TITLE
Set front & back default enviornment setting

### ISSUE THREAD

**Issue by seo2im** [ReactPiscine/ReactPscine#6]
## Description
Make basic setting focus each development documents

## Todo
- [x] make server reository(front is this repository)
- [x] check framework & write echo envionment subject / update each wiki
- [x] check lint & apply
- [ ] make basic environment of each
