### ISSUE TITLE
Set basic framework setting & directory setting

### ISSUE THREAD

**Issue by seo2im** [ReactPiscine/ReactPscine#7]
## Description
setting framework & directory structure

after work **check frame work** in #6 

## Todo
- [ ] install package for framework
- [ ] setting directory structure
- [ ] write page component
